language: ruby

dist: xenial

rvm: 2.6.3

cache:
  directories:
    - /home/travis/.rvm
    - /home/travis/.npm
    - /home/travis/.cache

install:
  - bundle install

before_script:
  - bundle exec rake db:migrate

script:
  - bundle exec rspec

bundler_args: --without production
