language: ruby

dist: xenial

rvm:
  - 2.5.5
  - 2.6.3

gemfile:
  - Gemfile
  - gemfiles/4.0.rails5.gemfile
  - gemfiles/4.1.rails5.gemfile
  - gemfiles/4.0.rails6.gemfile

cache:
  directories:
    - /home/travis/.rvm
    - /home/travis/.cache

before_script:
  - bundle exec rake db:migrate

script:
  - bundle exec rspec

bundler_args: --without production
