language: ruby

dist: xenial

cache:
  directories:
    - /home/travis/.rvm
    - /home/travis/.npm
    - /home/travis/.cache

install:
  - bundle install

before_script:
  - bundle exec rails db:migrate

script:
  - bundle exec rspec

bundler_args: --without production
